# A compose file for development

version: "3.1"

networks:
  merochat_network:
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  db:
    build:
      context: ..
      dockerfile: containers/postgresql.containerfile
    restart: always
    environment:
      POSTGRES_USER: merochat
      POSTGRES_PASSWORD: merochat
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      merochat_network:
        ipv4_address: 10.0.0.2
    ports:
      - 5432:5432


  # unfortunately, there is no purescript docker image for 0.15.x (only 0.14.x)
  # so we have to start from a node image and grab the release binary ourselves.
  merochat:
    container_name: merochat
    build:
      context: ..
      dockerfile: containers/merochat.containerfile
    volumes:
      - type: bind
        source: ..
        target: /merochat
    environment:
      DATABASE_HOST: "10.0.0.2"
    networks:
      merochat_network:
        ipv4_address: 10.0.0.3
    ports:
      - 8000:8000
      - 1339:1339
    # This is needed because spago run --watch is an interactive command.
    depends_on:
      - db

  # this is just for handling the db from a web gui
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      merochat_network:
        ipv4_address: 10.0.0.4
    depends_on:
      - db